title: Site

tabs:
  tab1:
    label: Pages
    sections:
      pages:
        type: pages
        width: 3/4

        # help: Select each page to edit the content. <br> To edit the homepage grid, first add the exhibition details in the 'Programs' page. <br>Next, navigate to the 'Trocadero Projects Home' section and select the desired program to include in the grid.<br>Please ensure it is selected in one of the first four positions. <br><br>To update the address in both the footer and the 'Visit' section, make the edits within the 'Footer' tab.

      files:
        type: files

      placeholder:
        type: fields
        fields:
          placeholder:
            help: Placeholder for pages with missing images.
            type: files
            layout: cards
            size: tiny
            max: 1
            required: true
            width: 1/4

  tab2:
    label: Home
    sections:
      options:
        type: fields
        fields:
          filter:
            label: Images
            type: toggle
            default: false
            width: 1/2
            text:
              - "greyscale"
              - "colour"
          theme:
            type: colors
            label: Theme
            alpha: true
            default: "#dfa280"
            # contrast: true
            width: 1/2
          manual:
            label: Homepage Layout
            type: toggle
            default: false
            text:
              - "automatic"
              - "manual"
          slice:
            label: Number of pages
            type: number
            default: 4
            width: 1/2
            help: Enter the number of pages to show on the home page. Pages will be displayed in chronological order.
            when:
              manual: false
          layout:
            type: pages
            size: large
            layout: cards
            query: site.find('program')
            when:
              manual: true
  tab3:
    label: Footer
    fields:
      # staticSiteGenerator:
      #   label: Generate a static version of the site
      footer_theme:
        type: colors
        label: Footer Background Colour
        alpha: true
        default: "#dfa280"
        # contrast: true
        width: 1/2
      acknowledgment:
        width: 1
        type: textarea
        size: small
      footerCopyright:
        width: 1/2
        label: Footer Copyright
        type: textarea
        size: small
      footerInfo:
        width: 1/2
        label: Footer Info
        type: textarea
        size: small
      footerLeft:
        width: 1/2
        label: Right Footer 1
        type: textarea
        size: small
      footerRight:
        width: 1/2
        label: Right Footer 2
        type: textarea
        size: small
      logos:
        type: files
        layout: cards
        help: Drag images to change order. The first image will be the thumbnail.
      facebook:
        width: 1/3
        label: Facebook link
        type: text
        size: small
      instagram:
        width: 1/3
        label: Instagram link
        type: text
        size: small
      youtube:
        width: 1/3
        label: Youtube link
        type: text
        size: small
      twitter:
        width: 1/3
        label: Twitter link
        type: text
        size: small
      soundcloud:
        width: 1/3
        label: Soundcloud link
        type: text
        size: small
      # layout:
      #   type: layout
      #   pretty: true
      #   layouts:
      #     - "1/1"
      #     - "1/2, 1/2"
      #     - "1/4, 1/4, 1/4, 1/4"
      #     - "1/3, 2/3"
      #     - "2/3, 1/3"
      #     - "1/3, 1/3, 1/3"
      #   settings:
      #     fields:
      #       class:
      #         type: text
      #         width: 1/2
      #       id:
      #         type: text
      #         width: 1/2
  tab4:
    label: About
    fields:
      modules:
        help: https://www.markdownguide.org/cheat-sheet/
        label: Layout
        type: layout
        layouts:
          - "1/1"
          - "1/2, 1/2"
          - "1/4, 1/4, 1/4, 1/4"
          - "1/2, 1/4, 1/4"
          - "1/4, 1/4, 1/2"
          - "1/3, 1/3, 1/3"
          - "1/3, 2/3"
          - "2/3, 1/3"
        fieldsets:
          heading:
            extends: blocks/heading
            fields:
              level:
                options:
                  - h1
                  - h2
                  - h3
          text: true
          markdown: true
          image:
            extends: blocks/image
            fields:
              ratio:
                empty: false
                options:
                  1/1: "1:1"
                  3/2: "3:2"
                  4/5: "4:5"
                  5/2: "5:2"

 

  seotab: seo
